services:
  # Banco de dados PostgreSQL
  - type: pserv
    name: n8n-database
    env: postgres      
    plan: starter
    region: oregon
    databaseName: postgres_db_p3ww  
    user: user_postgres          

  # Serviço Web n8n
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    autoDeploy: true
    
    # Disco persistente para dados
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
      
    # Variáveis de ambiente
    envVars:
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: NODE_ENV
        value: production  
          
      # Segurança e permissões
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
        
      # Logging
      - key: N8N_LOG_LEVEL
        value: info
        
      # Webhooks
      - key: WEBHOOK_URL
        sync: false