services:
  # Banco de dados PostgreSQL
  - type: pserv
    name: n8n-database
    plan: starter
    region: oregon
    ipAllowList: []

  # Serviço Web n8n
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    autoDeploy: true
    
    # Disco persistente para dados
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1    
      
    # Variáveis de ambiente
    envVars:
      # Configurações do servidor
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: NODE_ENV
        value: production
        
      # Configurações de banco de dados
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          name: n8n-database
          type: pserv
          property: host
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        fromService:
          name: n8n-database
          type: pserv
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          name: n8n-database
          type: pserv
          property: password
          
      # Segurança e permissões
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
        
      # Logging
      - key: N8N_LOG_LEVEL
        value: info
        
      # Webhooks
      - key: WEBHOOK_URL
        sync: false