services:
  # Serviço Web n8n
  - type: web
    name: n8n
    runtime: docker      
    plan: starter
    region: oregon
    autoDeploy: true
    
    # Disco persistente para dados
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
      
    # Variáveis de ambiente
    envVars:
      # Conecta ao banco de dados definido na seção 'databases' abaixo
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db_p3ww
          property: connectionString
          
      # Configurações do servidor
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: NODE_ENV
        value: production
          
      # Segurança e permissões
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
        
      # Logging
      - key: N8N_LOG_LEVEL
        value: info
        
      # Webhooks (O valor é injetado pelo Render, sync: false evita commits)
      - key: WEBHOOK_URL
        sync: false

# Seção dedicada para a definição do banco de dados
databases:
  - name: n8n-database
    databaseName: n8n     # Nome interno do banco de dados
    user: n8n_user        # Nome do usuário que será criado
    plan: starter
    region: oregon
    ipAllowList: []       # Impede o acesso externo ao banco de dados